### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Retroperspect** [HackerNews-lsd2017/hacker-news#12]
at around 14:40 your system seems to stop responding to requests. are your system down or is it the simulator programs fault

**Comment by teutzue** [comment]
this is due to us updating the system. The status reports to be "update"

**Comment by Ldaxar** [comment]
Hey @Retroperspect   

We were indeed performing a database update that resulted in temporarily unavailability of our Service.   

In future you can check the status of our server at http://46.101.28.25:8080/status and of course you are more than welcome to report "down" state or fishy behaviour in "Alive" state.

Thank you for your valuable input which is very important factor in continuous improvement of our solution.
