### ISSUE TITLE
Hackernews doesn't display any stories

### ISSUE THREAD

**Issue by Emmely2008** [HackerNews-lsd2017/hacker-news#13]
When opening the [hackernews website](http://fe-hacker-news.s3-website-eu-west-1.amazonaws.com/): 
No stories are displayed. When selecting something in the menu I get redirected to the login page.

Following information can be seen on the request to server:

Request URL:http://46.101.28.25:8080/getPosts?limit=30
Request Method:GET
Status Code:500 
Remote Address:46.101.28.25:8080
Referrer Policy:no-referrer-when-downgrade

Screen shots:
[
https://gyazo.com/d260b2f78ad10a22fcd4095f4cee7b39](https://gyazo.com/7e80e6506ebf2ac9c8db3bf57e1ad880)

[
https://gyazo.com/bd24f35649804cd10f6f1ba716e8b9c8](https://gyazo.com/bd24f35649804cd10f6f1ba716e8b9c8)

[
https://gyazo.com/0ac4ffaff7f21509f19deec489b3bc70](https://gyazo.com/0ac4ffaff7f21509f19deec489b3bc70)

**Comment by WillVill** [comment]
Hi Emmely2008,
The issue seems to stem from a database/server update we had been running. Earlier during the day. We believe that everything is no back up and running. Thanks bringing this to our attention.

**Comment by Ldaxar** [comment]
I close this issue because it is resolved.
