### ISSUE TITLE
uptime spike

### ISSUE THREAD

**Issue by Retroperspect** [HackerNews-lsd2017/hacker-news#14]
at 12:28 we noticed a very short down spike, where you upgrading the server?

also sorry for reporting every little detail, but assignments are assignments.

**Comment by Ldaxar** [comment]
Hi @Retroperspect 

Today I was making significant changes to our database and server. It resulted in many errors and crashes, so monitoring data from today can be at very least hectic. I just managed to fix all bugs in connection to latest update so from 16:40 everything should be fine.
