### ISSUE TITLE
Request per minute spike

### ISSUE THREAD

**Issue by Retroperspect** [HackerNews-lsd2017/hacker-news#16]
at 19:00 we observed a request per min at 3367...
what happened?

**Comment by teutzue** [comment]
we are doing the monitoring assignment and we are trying to crash the system

**Comment by Retroperspect** [comment]
affirmative but how are we suppose to help with the issue, I send a mail earlier about credentials from our group mail as it would help us identify the issue and report it in time, however the assignment seems muddy in the involvement we should have in helping to identify the issue. but do write to our mail if there's anything specific you want us to help with

**Comment by teutzue** [comment]
I have replied to your email with the information requested.

**Comment by Koziar** [comment]
ddos baby

**Comment by Koziar** [comment]
😈 ☠️ 💩 😈 ☠️ 💩 😈 ☠️ 💩 😈 ☠️ 💩 😈 ☠️ 💩 😈 ☠️ 💩 😈 ☠️ 💩 😈 ☠️ 💩 😈 ☠️

**Comment by Retroperspect** [comment]
as you only given us grafana credentials, which we already had from emmely talking with you guys I believe, I suspect we can't help much with this issue, I do hope our response time have reduced the amount of damage your system received, however it has not come back online yet which worries me, also why am I seeing additional thoursands of request on your system, you already crashed it for the assignment, no need to abuse the poor servers more than needed

**Comment by Koziar** [comment]
Ok, thanks for the quick response!

**Comment by Koziar** [comment]
Guys wtf,

How would you help us with this particular issue having the access to the
backend, to the droplet you mean?

We can't and we won't give you any credentials to our backend, you should
not need it. Grafana should be enough for you to monitor the state of the
application and at github you'll find the entire source code for it. Just
report any issues on github or send an email, and please stop asking for
the credentials to the backend. If you disagree with it or perhaps I've
missed something, please point at anything (that we have from the teacher)
that says we have to give you the credentials.

Best regards,
Lukas

**Comment by Ldaxar** [comment]
Based on conversation above I assume that this issue is resolved, therefore I close it.

If I am wrong and it is not resolved please open new issue.

Thank you for you input !
