### ISSUE TITLE
Missing some functionallity around comment

### ISSUE THREAD

**Issue by Emmely2008** [HackerNews-lsd2017/hacker-news#17]
Hi!
I'm looking at the display of stories and all the threads have 0 comments.

Aren't there suppose to be any comments on at least some of the stories?

[
https://gyazo.com/1f53332d7621db543bcc5b1549af4157](https://gyazo.com/1f53332d7621db543bcc5b1549af4157
)

**Comment by Koziar** [comment]
Yes, you're right. The mentioned functionality is still under the construction. Should be in production soon.

**Comment by Koziar** [comment]
btw, you can just drag the screenshot you took into the comment input field, you don't have to upload it every time to some other website :octocat: Like this: 
<img width="709" alt="screen shot 2017-11-14 at 14 32 44" src="https://user-images.githubusercontent.com/9032472/32782451-b80f1a14-c948-11e7-8466-83f01b296e63.png">

**Comment by Emmely2008** [comment]
Ok, thank for letting me know! 👍

**Comment by Ldaxar** [comment]
@Emmely2008 I am currently working on this feature. I will update you when I will be finished.

**Comment by Ldaxar** [comment]
@Emmely2008 
Comments are here! You are more than welcome to try them out.
