### ISSUE TITLE
Use Case: Log out - not working

### ISSUE THREAD

**Issue by Emmely2008** [HackerNews-lsd2017/hacker-news#18]
As seen in the screen shot the is a log out, but it's not functional. It seems to be just a text element.

Screen shots:

[
https://gyazo.com/84c41bd4a5b90c561cda532413f3c2dd](https://gyazo.com/84c41bd4a5b90c561cda532413f3c2dd )
[
https://gyazo.com/f12768474d7008df669311eabd965ed2](https://gyazo.com/f12768474d7008df669311eabd965ed2)

**Comment by Koziar** [comment]
Fixed 😉
