### ISSUE TITLE
Use Case: Update user - how do I do this?

### ISSUE THREAD

**Issue by Emmely2008** [HackerNews-lsd2017/hacker-news#19]
As a logged in user I haven't found any way to edit/update my information?

I cannot click on my username that appears in the menu after I have signed in to the system.

[
https://gyazo.com/2495f7a86eb05a5b5732f528d6c32789](https://gyazo.com/2495f7a86eb05a5b5732f528d6c32789)

**Comment by Emmely2008** [comment]
What is the status of this issue report?

**Comment by Ldaxar** [comment]
Hi @Emmely2008 

Sorry for long response time.

Right now I am focused on creating comment feature. I think that it is a crucial part of functionality so I have put my priority on that. Would you mind to wait 2-3 days until I resolve that issue?

**Comment by WillVill** [comment]
Implemented, closing the issue.
