### ISSUE TITLE
grafana down

### ISSUE THREAD

**Issue by Retroperspect** [HackerNews-lsd2017/hacker-news#25]
havn't paid much attention lately, but at 12:11 I check and grafana have lost data
check prometheus

**Comment by WillVill** [comment]
Back up

**Comment by Retroperspect** [comment]
it's down again... are you hosting it on dockerswarm without a volume of sort? cause I think we had the same issue where dockerswarm would move the container to another spot resulting in grafana and prom loosing thier connection
