### ISSUE TITLE
Minor keep alive thing label:question

### ISSUE THREAD

**Issue by Retroperspect** [HackerNews-lsd2017/hacker-news#5]
Been testing your sites TCP protocol calls, and I've noticed something strange with a keep alive state, I'm unfamiliar if it's correct to do, but I experience the following pattern.
using a web browser and connecting to the site, Wireshark tells me that 45 seconds after I got the websites info, my client sends a signal back to the server, then 10 seconds later I receive a message, and then 5 seconds later my client sends a final TCP call.  

the issue is it's not consistent, I experienced the second call go up to 16 seconds and the last call down to 1-2 seconds, so I'm unsure if there's something here, but it's worth looking into.

if you wish to check this I recommend using [https://www.wireshark.org/](url) and applying the following filter.
`(ip.dst == 46.101.28.25) || (ip.src == 46.101.28.25)`

**Comment by teutzue** [comment]
closing this since it was an antivirus related problem, will take care of when we fix #7
