### ISSUE TITLE
am I unable to assign labels?

### ISSUE THREAD

**Issue by Retroperspect** [HackerNews-lsd2017/hacker-news#6]
I'm unsure if I'm not seeing the way, I checked by going back to my previous issue [https://github.com/HackerNews-lsd2017/hacker-news/issues/5](url) but I seem to be unable to assign labels and people to the issue.

please allow the following users these features
https://github.com/DanielHauge
https://github.com/Retroperspect
https://github.com/Emmely2008

**Comment by WillVill** [comment]
Yo Retro, we have changed our documentation. The labels and assignment of people to the issue are for Admins of our project. Thanks for that 👍 🥇
