### ISSUE TITLE
Antivirus blocks IP

### ISSUE THREAD

**Issue by Retroperspect** [HackerNews-lsd2017/hacker-news#7]
My antivirus program was acting up when trying to access http://fe-hacker-news.s3-website-eu-west-1.amazonaws.com/ and i had to manually block this IP 46.101.28.25
after block it was fine, but I removed the block and could still access the site no problem, when I tried to connect to 46.101.28.25 it acted up again, specifically 46.101.28.25/favicon.ico
but after saying it should ignore I could connect just fine.
but it's not showing in my manuel block but it shows in my log, I'm able to connect to both http://fe-hacker-news.s3-website-eu-west-1.amazonaws.com and 46.101.28.25 no problems now, but I'll like to notify you there might be a issue here.

**Comment by WillVill** [comment]
I believe this issue could be fixed by using our new url: http://d3com7bor8tlib.cloudfront.net/
We would love to hear if this issue has been fixed.

**Comment by Retroperspect** [comment]
sadly not https://i.gyazo.com/254809554b721ed836423c4e1d20b69f.png

**Comment by Retroperspect** [comment]
Follow up, sorry for taking so long to verify but it's no longer a issue.
