### ISSUE TITLE
Register user - no user feedback

### ISSUE THREAD

**Issue by Emmely2008** [HackerNews-lsd2017/hacker-news#9]
When registering a user by filling in the Create Account form and submitting the form - no feedback is given to the user whether the account was created or not.

The form is not reset either.

**Comment by Ldaxar** [comment]
Hey @Emmely2008

I was able to replicate your issue. I have assigned our fronted experts that will take a look at it and try to resolve this issue as soon as possible.

Thank you for your input!

**Comment by WillVill** [comment]
This has been fixed! Thanks. The user is now logged in if registrations is successful.
